- name: "Copy netplan configuration"
  become: true
  ansible.builtin.template:
    src: "templates/netplan/00-installer-config.yaml.j2"
    dest: "/etc/netplan/00-installer-config.yaml"
  notify:
    - Restart host
- name: "Copy frr configuration"
  become: true
  ansible.builtin.template:
    src: "templates/frr/frr.conf.j2"
    dest: "/etc/frr/frr.conf"
  notify:
    - Restart frr
- name: Enable IPv4 forwarding
  become: true
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: yes
- name: Enable IPv6 forwarding
  become: true
  ansible.posix.sysctl:
    name: net.ipv6.conf.all.forwarding
    value: '1'
    sysctl_set: yes
- name: Enable strict ARP
  become: true
  ansible.posix.sysctl:
    name: net.ipv4.conf.all.arp_ignore
    value: '1'
    sysctl_set: yes
- name: Configure strict ARP
  become: true
  ansible.posix.sysctl:
    name: net.ipv4.conf.all.arp_announce
    value: '2'
    sysctl_set: yes
- name: "Copy nftables configuration"
  become: true
  ansible.builtin.template:
    src: "templates/nft/nftables.conf.j2"
    dest: "/etc/nftables.conf"
  notify:
    - Restart nftables
- name: "Enable nftables on boot"
  become: true
  ansible.builtin.service:
    name: nftables
    enabled: yes
- name: "Install dnsmasq"
  become: true
  ansible.builtin.apt:
    pkg:
      - dnsmasq
- name: "Enable dnsamasq on boot"
  become: true
  ansible.builtin.service:
    name: dnsmasq
    enabled: yes
- name: "Copy dnsmasq configuration"
  become: true
  ansible.builtin.template:
    src: "templates/dnsmasq/dnsmasq.conf.j2"
    dest: "/etc/dnsmasq.conf"
  notify:
    - Restart dnsmasq
