# Install playbook for WiMoVE
---
# Install frr on the gateway and the route reflectors
- hosts: ubuntu
  name: "Base setup frr"
  roles:
    - frr-setup
# Setup all services on the gateway
- hosts: gateways
  name: "Configure gateway"
  roles:
    - gateway
- hosts: openwrt
  roles:
    - access-point
