# Install playbook for WiMoVE
---
# Install frr on the gateway and the route reflectors
- hosts: ubuntu
  name: "Base setup frr"
  roles:
    - frr-setup
# FRR setup on the route reflectors
- hosts: routeReflectors
  name: "Copy FRR config"
  roles:
    - route-reflector
# Setup all services on the gateway
- hosts: gateways
  name: "Configure gateway"
  roles:
    - gateway
- hosts: gateways:&routeReflectors
  name: "Configure combined gateway and route reflector"
  roles:
    - combined
- hosts: openwrt
  roles:
    - access-point
