# Install playbook for WiMoVE
---
# Install frr on the gateway and the route reflectors
- hosts: ubuntu
  name: "Base setup frr"
  roles:
    - frr-setup
# FRR setup on the route reflectors
- hosts: routeReflectors
  name: "Copy FRR config"
  roles:
    - route-reflector
# Setup all services on the gateway
- hosts: gateways
  name: "Configure gateway"
  roles:
    - gateway
# Copy WiMoVE package on to the Zyxel APs
- hosts: zyxel
  name: "Copy wimoved to zyxel"
  tasks:
    - name: copy wimoved for NWA
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "/tmp/wimoved.ipk"
      with_fileglob: "./zyxel/*.ipk"
# Copy WiMoVE package on to the Linksys APs
- hosts: linksys
  name: "Copy wimoved to linksys"
  tasks:
    - name: copy wimoved for ACS
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "/tmp/wimoved.ipk"
      with_fileglob: "./linksys/*.ipk"
# General OpenWRT setup
- hosts: openwrt
  roles:
    - access-point
# Copy configuration for OpenWRT onto zyxel APs
- hosts: zyxel
  name: "Applying openwrt config"
  tasks:
    - name: import openwrt config
      uci:
        command: import
        value: "{{ lookup ('template', './zyxel/conf-ota.j2') }}"
    - name: commit changes
      uci:
        command: commit
      notify:
        - reload wifi
        - reload network

# Copy configuration for OpenWRT onto linksys APs
- hosts: linksys
  name: "Applying openwrt config"
  tasks:
    - name: import openwrt config
      uci:
        command: import
        value: "{{ lookup ('template', './linksys/conf-ota.j2') }}"
    - name: commit changes
      uci:
        command: commit
      notify:
        - reload wifi
        - reload network

- hosts: openwrt
  name: "Rebooting all APs"
  tasks:
    - name: reboot
      command: reboot
