---
- name: Restart nftables
  become: true
  ansible.builtin.service:
    name: nftables
    state: restarted
- name: Restart frr
  become: true
  ansible.builtin.service:
    name: frr
    state: restarted
- name: Restart host
  become: true
  ansible.builtin.reboot:
- name: Restart dnsmasq
  become: true
  ansible.builtin.service:
    name: dnsmasq
    state: restarted