- name: "Install frr"
  become: true
  ansible.builtin.apt:
    pkg:
      - frr
- name: "Enable frr on boot"
  become: true
  ansible.builtin.service:
    name: frr
    enabled: yes
- name: "Copy daemons"
  become: true
  ansible.builtin.copy:
    src: "files/frr/daemons"
    dest: "/etc/frr/daemons"
  notify:
    - Restart frr